# Podman Compose configuration for CMS
# This configuration runs the backend service with PostgreSQL

services:
    # PostgreSQL Database Service
    cms-db:
        image: docker.io/postgres:15-alpine
        container_name: cms-db
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdb
            - POSTGRES_USER=cms_user
            - POSTGRES_PASSWORD=cms_password
            - POSTGRES_DB=cms_db
        volumes:
            # Map data volume for persistent database storage
            - cms_data:/var/lib/postgresql/data:Z
            # Initialize database schema
            - ./src/backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:Z
        restart: unless-stopped
        networks:
            - cms_network
        ports:
            # Expose PostgreSQL port for external access (optional, for development)
            - "5432:5432"

    # CMS Backend Service
    cms-backend:
        build:
            context: .
            dockerfile: Containerfile
        image: localhost/cms-backend:latest
        container_name: cms-backend
        ports:
            - "3000:3000"
        depends_on:
            - cms-db
        environment:
            # Database Configuration
            - DB_HOST=cms-db
            - DB_PORT=5432
            - DB_NAME=cms_db
            - DB_USER=cms_user
            - DB_PASSWORD=cms_password
            
            # JWT Configuration
            - JWT_SECRET=cms-jwt-secret-change-in-production
            - JWT_EXPIRES_IN=24h
            
            # Server Configuration
            - PORT=3000
            - NODE_ENV=production
            
            # CORS Configuration
            - CORS_ORIGIN=http://localhost:8080
        restart: unless-stopped
        networks:
            - cms_network

# Named volumes for persistent data storage
volumes:
    cms_data:
        driver: local

# Network for inter-container communication
networks:
    cms_network:
        driver: bridge

